package autolotto.machine;

import autolotto.machine.lotto.Lotto;
import autolotto.machine.lotto.LottoGenerator;
import autolotto.machine.lotto.fixture.FixedNumberShuffler;
import autolotto.machine.winning.Winning;
import autolotto.machine.winning.WinningNumbers;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
public class LottoMachineTest {

    private final Integer bonusNumberAnyLottoNotContaining = 11;

    private final static int LOTTO_PRICE = 1000;

    private final int manualCount = 0;

    @Test
    void 금액에_따라_로또를_생성해_갖고_있다() {
        int inputMoney = 2000;

        LottoMachine lottoMachine =
                new LottoMachine(manualCount, new LottoGenerator(new FixedNumberShuffler()), inputMoney);

        List<Lotto> createdLotteries = lottoMachine.lotteries();

        Assertions.assertThat(createdLotteries).hasSize(inputMoney / LOTTO_PRICE);
    }

    @Test
    void 총_로또의_개수를_알려준다() {
        int inputMoney = 2000;

        LottoMachine lottoMachine =
                new LottoMachine(manualCount, new LottoGenerator(new FixedNumberShuffler()), inputMoney);

        Assertions.assertThat(lottoMachine.totalLottoCount()).isEqualTo(inputMoney / LOTTO_PRICE);
    }


    @Nested
    class AutoGeneratedLottoNumberTest {

        private final int expectedTotalCount = 10;

        @Test
        void F_수동로또의_개수가_음수로_주어진_경우_로또머신_생성에_실패한다() {
            int anyInputMoney = 10000;
            int invalidManualCount = -1;

            Assertions.assertThatExceptionOfType(IllegalArgumentException.class)
                    .isThrownBy(() -> new LottoMachine(
                            invalidManualCount,
                            new LottoGenerator(new FixedNumberShuffler()),
                            anyInputMoney
                    ));
        }

        @Test
        void F_수동로또의_개수가_총_로또_개수보다_큰_경우_로또머신_생성에_실패한다() {
            int inputMoney = expectedTotalCount * LOTTO_PRICE;

            Assertions.assertThatExceptionOfType(IllegalArgumentException.class)
                    .isThrownBy(() -> new LottoMachine(
                            expectedTotalCount + 1,
                            new LottoGenerator(new FixedNumberShuffler()),
                            inputMoney));
        }

        @Test
        void S_유효한_수동로또의_개수가_주어져_생성된_로또머신은_자동_로또_개수를_알려준다() {
            int manualCount = 6;
            LottoMachine lottoMachine = new LottoMachine(manualCount, new LottoGenerator(new FixedNumberShuffler()), expectedTotalCount * LOTTO_PRICE);

            int autoCount = lottoMachine.autoLottoCount();

            Assertions.assertThat(autoCount)
                    .isEqualTo(expectedTotalCount - manualCount);
        }
    }

    @Nested
    class ManuallyGeneratedLottoTest {

    }

    @Test
    void 당첨번호가_주어지면_수익률을_소수점_둘째_자리까지_반올림한_값으로_알려준다() {
        LottoMachine lottoMachine = new LottoMachine(manualCount, new LottoGenerator(new FixedNumberShuffler()), 3000);
        BigDecimal expectedProfitRate = BigDecimal.valueOf((double) Winning.THREE.winningMoney() * 3 / 3000).setScale(2);
        WinningNumbers winningNumbers = new WinningNumbers(Arrays.asList(1, 2, 3, 21, 22, 23), bonusNumberAnyLottoNotContaining);

        BigDecimal profitRate = lottoMachine.profitRate(winningNumbers);

        Assertions.assertThat(profitRate).isEqualTo(expectedProfitRate);
    }

    @Test
    void 당첨번호가_주어지면_일치_개수별_로또_개수를_알려준다() {
        LottoMachine lottoMachineWithSameThreeLotto = new LottoMachine(manualCount, new LottoGenerator(new FixedNumberShuffler()), 3000);
        WinningNumbers winningNumbers = new WinningNumbers(Arrays.asList(1, 2, 3, 21, 22, 23), bonusNumberAnyLottoNotContaining);

        Map<Winning, Integer> numberOfEachMatchingCount = lottoMachineWithSameThreeLotto.winningState(winningNumbers);

        Assertions.assertThat(numberOfEachMatchingCount.get(Winning.THREE)).isEqualTo(3);
    }
}
